upgrade package.js for meteor 1.2
https://github.com/meteor/meteor/wiki/Breaking-changes-in-Meteor-1.2
PackageAPI#addAssets (change required to package.js file): In packages,
files added with api.addFiles that have no recognizable extension are no
longer added as static assets. You must now use api.addAssets to add a
static asset.

While building package horka:swipebox:
error: No plugin known to handle file 'swipebox/img/loader.gif'. If you
want this file to be a static asset, use
addAssets instead of addFiles; eg,
api.addAssets('swipebox/img/loader.gif', 'client').
error: No plugin known to handle file 'swipebox/img/icons.png'. If you
want this file to be a static asset, use
addAssets instead of addFiles; eg,
api.addAssets('swipebox/img/icons.png', 'client').
error: No plugin known to handle file 'swipebox/img/icons.svg'. If you
want this file to be a static asset, use
addAssets instead of addFiles; eg,
api.addAssets('swipebox/img/icons.svg', 'client').